module.exports = {
  QUIZ_RECIEVED: "QUIZ_RECIEVED",
  QUESTION_RESULT_RECIEVED: "QUESTION_RESULT_RECIEVED",
  ALL_QUESTION_RESULTS_RECIEVED: "ALL_QUESTION_RESULTS_RECIEVED",
  USER_QUIZ_RECIEVED: "USER_QUIZ_RECIEVED"
}
